# site settings
title: Interrupt LLC.
subtitle:
email: info@interrupt.technology
theme: forty_jekyll_theme
description: 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.interrupt.technology" # the base hostname & protocol for your site
author: Naoko Kubo
#street_address:
#city: 日野市
#state: 東京都
#zip_code: 191-0041
#country: 日本
#phone:
future: true
# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 7

# build settings
markdown: kramdown
kramdown:
 auto_ids: true
 hard_wrap: true
 syntax_highlighter: rouge

sass:
  style: compressed

###QandASlack
qandaslack:
- question: Slackについて
  answer: '申し込みフォームからお申し込み頂きますと、Interruptから入金のご案内メールをお送り致します。振込先への入金が確認できましたら、再度メールをお送り致します。<br>そのメールに添付の開発委託に関する契約書、NDA(秘密保持)契約書をご確認の上、<br>メール内に記載の電子署名用URLから各契約書へご署名頂き、<br>弊社にて以上のご確認が取れましたら契約完了となり、チャットサービスのご案内メールを速やかにお送り致します。<br>'
- question: 契約更新・お支払いについて
  answer: 申し込みフォームからお申し込み頂きますと、Interruptからメールをお送り致します。<br>添付の開発の委託に関する契約書、NDA(秘密保持)契約書のご確認、<br>メール内に記載の電子署名用URLから各契約書へのご署名、記載の振込先への料金のお振込をお願い致します。<br>以上のご確認が取れ次第契約完了となり、速やかにチャットサービスのご用意をさせて頂きます。
- question: 大きな開発のご依頼について
  answer: 申し込みフォームからお申し込み頂きますと、Interruptからメールをお送り致します。<br>添付の開発の委託に関する契約書、NDA(秘密保持)契約書のご確認、<br>メール内に記載の電子署名用URLから各契約書へのご署名、記載の振込先への料金のお振込をお願い致します。<br>以上のご確認が取れ次第契約完了となり、速やかにチャットサービスのご用意をさせて頂きます。

###QandA
qanda:
- question: 契約までの流れ
  answer:  申し込みフォームからお申し込み頂きますと、Interruptから入金のご案内メールをお送り致します。振込先への入金が確認できましたら、再度メールをお送り致します。<br>そのメールに添付の開発委託に関する契約書、NDA(秘密保持)契約書をご確認の上、<br>メール内に記載の電子署名用URLから各契約書へご署名頂き、<br>弊社にて以上のご確認が取れましたら契約完了となり、チャットサービスのご案内メールを速やかにお送り致します。<br>
- question: 契約更新とお支払い
  answer:  WithDOでは、ご入金を確認後にこちらから契約書をお送りする日の翌日を契約日とし、毎月同日を契約更新日と致します。<br>(例：4/1にお申し込み頂いた場合、契約更新日は更新月の1日が更新日となります。※ご契約日が31日などで、更新月が31日までない場合は更新月末日に繰り上げ。)<br>また、次回更新料のお支払いは、契約時にご入金頂いた弊社お振込先に、次回更新日の前日までにご入金をお願い致します。<br>
- question: 使用するチャットサービス
  answer: WithDOでのチャットサービスは全て「Slack」を使用します。<br>申し込みフォームにSlackアカウントについての項目がございますので、お申し込みの際はアカウントの有無やご登録のアドレスについてお答えください。<br>アカウントをお持ちでない場合は、ご契約完了後に申し込みフォームでご記載頂いたメールアドレスを使用し、弊社にてアカウントを作成致します。<br>Slackについてのご不明点については、弊社お問い合わせよりご質問頂くか、以下Slack公式ヘルプをご覧ください。<br><a href="https://slack.com/intl/ja-jp/" target="_blank"><i class="fas fa-question-circle"></i>Slack公式ページ</a><br><a href="https://slack.com/intl/ja-jp/help/articles/115004071768-Slack-%E3%81%A3%E3%81%A6%E4%BD%95%EF%BC%9F" target="_blank"><i class="fas fa-question-circle"></i>Slackって何？(公式ヘルプ)</a>
- question: 大きな開発のご依頼について
  answer: With DOでご用意の工数では足りないなどの懸念がある場合、With DOではプラン別に追加工数をご用意しております。<br>追加工数は1日単位でご購入可能です。各プランでの追加工数の料金はプラン紹介にてご確認ください。<br>また、工数を追加しても足りないような規模の大きな開発のご依頼は、With DOとは別途のご契約で承ります。<br>お問い合わせまたはWith DOチャットサービスよりお気軽にご相談ください。<br>
- question: プラン変更
  answer: ご契約中のWith DOのコースをご変更されたい場合は、次回契約更新日の14日前までにチャットサービスよりご相談ください。<br>現在行なっている作業とコース変更後のご依頼内容、工数を見積もり、いつからどのプランへ変更するのが最適かご一緒に検討致します。<br>(※既にお支払い済みのご契約プランのグレードダウンと、それに伴う返金は行なっておりません。プラン変更の旨をご相談の上、次回更新時までお待ちください。)<br>
- question: 解約方法
  answer: 解約のお申し出は、次回契約更新日の14日前までにチャットサービスよりご相談ください。<br>現在行なっている作業の引き継ぎや運用物のクローズなどについて擦り合わせを行い、解約日をご一緒に検討致します。<br>(※既にお支払い済みのご契約プランの解約に伴う返金は行なっておりません。)<br>
###Contact
contactType:
- name: お問い合わせ内容を選択してください
- name: With DOについて
- name: 開発のご依頼について
- name: Interruptの開発物について
- name: 利用規約/プライバシーポリシーについて
- name: その他

###Course
course:
- name: デベロッパープラン
  description: アプリやWebサイト、社内用システムツールの新規開発や大型アップデートなど、大きな工数が必要な開発のご依頼にオススメなコースです。<br>稼働工数も月に4人日と全コース内で最も多く、全てのサービスがご利用可能となっているため、私たちが最もお力になれるコースです。<br>ご依頼の開発物が「4人日では足りないかもしれない…！」という場合には、他のコースよりお安く工数の追加をご検討頂けます。
  header_class: styledo1
  table_include: table_develop
  image: /assets/images/develop.jpg
  name_en: develop
  color: colordo1
  tabclass: tab-label1
  price: ■ 月額：150,000円/月
  man-days: ■ 稼働工数：4人日/月
  update: ■ 契約更新：１ヶ月単位
  addition1: 30,000円 + 税 / 1人日
  addition2: 33,000円 + 税 / 1人日

- name: デベロッパープランmin
  description: 既存アプリやWebサイトの運用や保守、簡単なツールの開発などにオススメのコースです。<br>大きな新規開発などのご依頼も承れますが、稼働工数が2日間のためゆっくりな開発となるでしょう。<br>迅速な開発をご要望の方は通常の「デベロッパーコース」をお勧め致します。<br>「デベロッパーコース」での新規開発が落ち着いてきたら、こちらに切り替えて運用していくのもいいかもしれません。
  header_class: styledo2
  table_include: table_develop_min
  image: /assets/images/developmin.jpg
  name_en: developmin
  color: colordo2
  tabclass: tab-label2
  price: ■ 月額：90,000円/月
  man-days: ■ 稼働工数：2人日/月
  update: ■ 契約更新：３ヶ月毎
  addition1: 33,000円 + 税 / 1人日
  addition2: 36,000円 + 税 / 1人日

- name: アジャストプラン
  description: 新しく業務を行う上での環境構築や新規ソフトウェアの導入サポートに加え、データ入力やデバッグのような細かな作業など、<br>「ちょっとそこまで手が回らない…！」という状況にオススメのコースです。<br>稼働工数は1日ですが、チャットサポートはご契約中いつでも使えますので環境構築後、ソフト導入後の不明点にもしっかりお答えします。
  header_class: styledo3
  table_include: table_adjust
  image: /assets/images/adjust.jpg
  name_en: adjust
  color: colordo3
  tabclass: tab-label3
  price: ■ 月額：50,000円/月
  man-days: ■ 稼働工数 1人日/月
  update: ■ 契約更新：３ヶ月毎
  addition1: 22,000円 + 税 / 1人日
  addition2: 24,000円 + 税 / 1人日
- name: メンタープラン
  description: Interruptの開発メンバーがIT分野の質問・相談に迅速にお答えします。<br>ベンチャーなどの企業において「作業は自社チームで行う予定だけど、有識者がいない…」「人手が足りなくて中々新人教育に注力できない」など、<br>そんな時代わりに我々がお答え致します。<br>企業に限らず、個人で学習中の方のメンターとしてもご協力致します。
  header_class: styledo4
  table_include: table_mentor
  image: /assets/images/mentor.jpg
  name_en: mentor
  color: colordo4
  tabclass: tab-label4
  price: ■ 月額：30,000円/月
  man-days: ー
  update: ■ 契約更新：３ヶ月毎
  addition1: ー
  addition2: ー


tooltip:
- name: 稼働工数
  description: 1人日＝8時間の稼働時間。<br>例1：1日に当社メンバー1名が3時間、1名が5時間稼働した場合、3時間+5時間＝8時間の為、1人日消費。<br>例2：1日に当社メンバー2名が8時間ずつ稼働した場合、8時間×2名＝16時間の為、1日で2人日消費。<br>※端数は30分単位で切り上げして換算。
- name: チャットサポート
  description: ２４時間いつでも、ITに関連する質問やご相談を受け付け、現在のお悩みごとの解決に協力致します。<br>一人で学習中の方のメンターとしてもご利用頂けます。<br>※回答は可能な限り迅速にお返ししますが、内容や時間帯によってお時間を頂戴する場合がございます。<br>※チャットサービスは当社から指定したサービスでのみ対応させていただきます。
- name: 環境構築
  description: Git,Jenkinsなど管理用のサーバー作成、ツールの導入やセットアップなどを承ります。<br>簡単なブログやWebページの新規設立はこちらで対応可能な場合もあります。<br>詳しくはお問い合わせください。
- name: 業務サポート
  description: バナーや表示の差し替えなど運用中のWebサイトの簡単な改修から、<br>データ入力業務や表計算入力、既存ソフトの設定変更、既存システムの改修、<br>リリース前の製品のデバッグなどの細かな作業を承りサポート致します。
- name: ソフトウェア相談
  description: 業務改善などで新規にソフトウェアやSaasの導入を検討する際、<br>最適なソフトのご提案から導入のご支援、導入後のレクチャーやケアまで承ります。
- name: 業務ツール開発
  description: 社内用業務ツールの新規開発から、その後の運用サポートまで承ります。<br>例えば「Zoom会議室に誰かが入退室したら、Slackに通知する。」など、<br>ご利用中のソフトウェアと連携したツールの作成もご相談ください。<br>Excelのマクロ作成も承ります。
- name: WEBアプリ新規開発
  description: 新規Webサイトやアプリの開発を承ります。<br>要件定義や仕様設計などから承ることもできますし、ご用意のある資料から開発を承ることも可能です。
- name: 追加工数について
  description: 追加料金をお支払頂くことで、各プランで用意されている稼働工数時間にさらに追加での稼働を承ります。<br>稼働工数は1人日から追加可能で、ご加入のプランの稼働工数の1人日単価の0〜20%増しの価格で承っております。<br>(ご加入のプランと、前月予約か当月追加かによって前後致します。)<br>ご追加の際は、チャットサービスやビデオMTGにてお気軽にご相談ください。
- name: ビデオMTG
  description: 企画や仕様の擦り合わせや、開発作業の進捗のご報告MTGをオンラインで実施します。<br>契約後ご都合のいい曜日や時間をお伺いし、週次で行う予定です。<br>また、隔週でも良い、不要などのご希望あればその旨もご相談ください。<br>なお、何か不具合などの発生で必要な場合は、本MTGとは別に実施可能です。<br>

plan:
- name: develop
  pricedesc:
    title: 料金内訳
    description: 【チャットサポート30,000円】＋【開発工数30,000円/1人日×4人日】
  addition1:
    title: 料金内訳
    description: 開発工数30,000円/1人日 + 10%
  addition2:
    title:  料金内訳
    description: 開発工数30,000円/1人日 + 20%
  update:
    title: 契約更新
    description: 毎月1ヶ月分の料金のお支払いをお願い致します。お支払日はご契約日によって異なります。<br>ご契約の詳細については「Information」をご確認ください。
- name: developmin
  pricedesc:
    title: 料金内訳
    description: 料金内訳：【チャットサポート30,000円】＋【開発工数30,000円/1人日×2人日】
  addition1:
    title: 料金内訳
    description: 開発工数30,000円/1人日 + 10%
  addition2:
    title:  料金内訳
    description: 開発工数30,000円/1人日 + 20%
  update:
    title: 契約更新
    description:  3ヶ月毎に3ヶ月分の料金のお支払いをお願い致します。お支払日はご契約日によって異なります。<br>ご契約の詳細については「Information」をご確認ください。<br>※初回1ヶ月無料キャンペーン対象プランのため、初回のみ3ヶ月+1ヶ月(無料)の計4ヶ月の契約となります。
- name: adjust
  pricedesc:
    title: 料金内訳
    description: 【チャットサポート30,000円】＋【作業工数20,000円/1人日】
  addition1:
    title: 料金内訳
    description: 開発工数20,000円/1人日 + 10%
  addition2:
    title:  料金内訳
    description: 開発工数20,000円/1人日 + 20%
  update:
    title: 契約更新
    description:  3ヶ月毎に3ヶ月分の料金のお支払いをお願い致します。お支払日はご契約日によって異なります。<br>ご契約の詳細については「Information」をご確認ください。<br>※初回1ヶ月無料キャンペーン対象プランのため、初回のみ3ヶ月+1ヶ月(無料)の計4ヶ月の契約となります。
- name: mentor
  pricedesc:
    title: 料金内訳
    description: 【チャットサポート30,000円】のみ
  addition1:
    title:
    description:
  addition2:
    title:
    description:
  update:
    title: 契約更新
    description:  3ヶ月毎に3ヶ月分の料金のお支払いをお願い致します。お支払日はご契約日によって異なります。<br>ご契約の詳細については「Information」をご確認ください。<br>※初回1ヶ月無料キャンペーン対象プランのため、初回のみ3ヶ月+1ヶ月(無料)の計4ヶ月の契約となります。
