# site settings
title: Interrupt LLC.
subtitle:
email: info@interrupt.technology
theme: forty_jekyll_theme
description: 経験豊富なメンバーが<br />ITに関するベストソリューションをご提案します。
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.interrupt.technology" # the base hostname & protocol for your site
author: Naoko Kubo
#street_address:
#city: 日野市
#state: 東京都
#zip_code: 191-0041
#country: 日本
#phone:
future: true
# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 7

# build settings
markdown: kramdown
kramdown:
 auto_ids: true
 hard_wrap: true
 syntax_highlighter: rouge

sass:
  style: compressed

###QandA
qanda:
- question: 契約までの流れについて
  answer: 申し込みフォームからお申し込み頂きますと、Interruptからメールをお送り致します。<br>添付の開発の委託に関する契約書、NDA(秘密保持)契約書のご確認、<br>メール内に記載の電子署名用URLから各契約書へのご署名、記載の振込先への料金のお振込をお願い致します。<br>以上のご確認が取れ次第契約完了となり、速やかにチャットサービスのご用意をさせて頂きます。

- question: 契約更新・お支払いについて
  answer: 申し込みフォームからお申し込み頂きますと、Interruptからメールをお送り致します。<br>添付の開発の委託に関する契約書、NDA(秘密保持)契約書のご確認、<br>メール内に記載の電子署名用URLから各契約書へのご署名、記載の振込先への料金のお振込をお願い致します。<br>以上のご確認が取れ次第契約完了となり、速やかにチャットサービスのご用意をさせて頂きます。
- question: 大きな開発のご依頼について
  answer: 申し込みフォームからお申し込み頂きますと、Interruptからメールをお送り致します。<br>添付の開発の委託に関する契約書、NDA(秘密保持)契約書のご確認、<br>メール内に記載の電子署名用URLから各契約書へのご署名、記載の振込先への料金のお振込をお願い致します。<br>以上のご確認が取れ次第契約完了となり、速やかにチャットサービスのご用意をさせて頂きます。

###Contact
contactType:
- name: --お問い合わせ内容を選択してください
- name: With DOについて
- name: 開発のご依頼について
- name: Interruptの開発物について

###Course
course:
- name: デベロッパーコース
  description: アプリやWebサイト、社内用システムツールの新規開発や大型アップデートなど、大きな工数が必要な開発のご依頼にオススメなコースです。<br>稼働工数も月に4人日と全コース内で最も多く、全てのサービスがご利用可能となっているため、私たちが最もお力になれるコースです。<br>ご依頼の開発物が「4人日では足りないかもしれない…！」という場合には、他のコースよりお安く工数の追加をご検討できます。
  header_class: styledo1
  table_include: table_develop
  image: /assets/images/goran-ivos-T8LMIN09-mo-unsplash.jpg
- name: デベロッパーコースmin
  description: 既存アプリやWebサイトの運用や保守、簡単なツールの開発などにオススメのコースです。<br>大きな新規開発などのご依頼も承れますが、稼働工数が2日間のためゆっくりな開発となるでしょう。<br>迅速な開発をご要望の方は通常の「デベロッパーコース」をお勧め致します。<br>「デベロッパーコース」での新規開発が落ち着いてきたら、こちらに切り替えて運用していくのもいいかもしれません。
  header_class: styledo2
  table_include: table_develop_min
  image: /assets/images/goran-ivos-T8LMIN09-mo-unsplash.jpg
- name: アジャストコース
  description: 　新しく業務を行う上での環境構築や新規ソフトウェアの導入サポートに加え、データ入力やデバッグのような細かな作業など、<br>「ちょっとそこまで手が回らない…！」という状況にオススメのコースです。<br>稼働工数は1日ですが、チャットサポートはご契約中いつでも使えますので環境構築後、ソフト導入後の不明点にもしっかりお答えします。
  header_class: styledo3
  table_include: table_adjust
  image: /assets/images/goran-ivos-T8LMIN09-mo-unsplash.jpg
- name: メンターコース
  description: 　Interruptの開発メンバーがIT分野の質問・相談に迅速にお答えします。<br>ベンチャーなどの企業において「作業は自社チームで行う予定だけど、有識者がいない…」「人手が足りなくて中々新人教育に注力できない」など、<br>そんな時代わりに我々がお答え致します。<br>企業に限らず、個人で学習中の方のメンターとしてもご協力致します。
  header_class: styledo4
  table_include: table_mentor
  image: /assets/images/goran-ivos-T8LMIN09-mo-unsplash.jpg


tooltip:
- name: 稼働工数
  description: 1人日＝8時間の稼働時間。<br>例1：1日に当社メンバー1名が3時間、1名が5時間稼働した場合、3時間+5時間＝8時間の為、1人日消費。<br>例2：1日に当社メンバー2名が8時間ずつ稼働した場合、8時間×2名＝16時間の為、1日で2人日消費。<br>※端数は30分単位で切り上げして換算。
- name: チャットサポート
  description: ２４時間いつでも、ITに関連する質問やご相談を受け付け、現在のお悩みごとの解決に協力致します。<br>一人で学習中の方のメンターとしてもご利用頂けます。<br>※回答は可能な限り迅速にお返ししますが、内容や時間帯によってお時間を頂戴する場合がございます。<br>※チャットサービスは当社から指定したサービスでのみ対応させていただきます。
- name: 環境構築
  description: Git,Jenkinsなど管理用のサーバー作成、ツールの導入やセットアップなどを承ります。<br>簡単なブログやWebページの新規設立はこちらで対応可能な場合もあります。<br>詳しくはお問い合わせください。
- name: 業務サポート
  description: バナーや表示の差し替えなど運用中のWebサイトの簡単な改修から、<br>データ入力業務や表計算入力、既存ソフトの設定変更、既存システムの改修、<br>リリース前の製品のデバッグなどの細かな作業を承りサポート致します。
- name: ソフトウェア相談
  description: 業務改善などで新規にソフトウェアやSaasの導入を検討する際、<br>最適なソフトのご提案から導入のご支援、導入後のレクチャーやケアまで承ります。
- name: 業務ツール開発
  description: 社内用業務ツールの新規開発から、その後の運用サポートまで承ります。<br>例えば「Zoom会議室に誰かが入退室したら、Slackに通知する。」など、<br>ご利用中のソフトウェアと連携したツールの作成もご相談ください。<br>Excelのマクロ作成も承ります。
- name: WEBアプリ新規開発
  description: 新規Webサイトやアプリの開発を承ります。<br>要件定義や仕様設計などから承ることもできますし、ご用意のある資料から開発を承ることも可能です。
- name: 追加工数料金<br>（翌月）
  description: 各コースで用意されている工数では不足が懸念される場合、事前にご予約頂くことで<br>翌月の工数を確保することが可能です。工数の確保は契約中チャットやMTGでご相談ください。<br>※当社スケジュールによって、ご予約頂けない場合がございます。ご了承ください。
- name: 追加工数料金<br>（当月）
  description: 実作業に当たってみたら予定よりも工数が必要な場合や、不具合が発生し急遽修正が必要な場合、<br>工数を追加することが可能です。工数の追加は契約中チャットやMTGでご相談ください。<br>※当社スケジュールによって、承れない場合がございます。ご了承ください。<br>

plan:
- name: develop
  pricedesc:
    title: 料金内訳
    description: 【チャットサポート30,000円】＋【開発工数30,000円/1人日×4人日】
  addition1:
    title: 料金内訳
    description: 開発工数30,000円/1人日 + 10%
  addition2:
    title:  料金内訳
    description: 開発工数30,000円/1人日 + 20%
  update:
    title: 契約更新
    description: 1ヶ月毎に1ヶ月分の料金が発生致します。料金の支払日は更新日によって異なります。<br>(Q&A参照)<br>※解約、コースの変更は支払日の5営業日前までにご申告ください。
- name: developmin
  pricedesc:
    title: 料金内訳
    description: 料金内訳：【チャットサポート30,000円】＋【開発工数30,000円/1人日×2人日】
  addition1:
    title: 料金内訳
    description: 開発工数30,000円/1人日 + 10%
  addition2:
    title:  料金内訳
    description: 開発工数30,000円/1人日 + 20%
  update:
    title: 契約更新
    description:  3ヶ月毎に3ヶ月分の料金が発生致します。料金の支払日は更新日によって異なります。<br>(Q&A参照)<br>なお初回1ヶ月無料キャンペーンにつき、初回契約時のみ3ヶ月+無料1ヶ月の計4ヶ月の契約となります。<br>※解約、コースの変更は支払日の5営業日前までにご申告ください。
- name: adjust
  pricedesc:
    title: 料金内訳
    description: 【チャットサポート30,000円】＋【作業工数20,000円/1人日】
  addition1:
    title: 料金内訳
    description: 開発工数20,000円/1人日 + 10%
  addition2:
    title:  料金内訳
    description: 開発工数20,000円/1人日 + 20%
  update:
    title: 契約更新
    description:  3ヶ月毎に3ヶ月分の料金が発生致します。料金の支払日は更新日によって異なります。<br>(Q&A参照)<br>なお初回1ヶ月無料キャンペーンにつき、初回契約時のみ3ヶ月+無料1ヶ月の計4ヶ月の契約となります。<br>※解約、コースの変更は支払日の5営業日前までにご申告ください。
- name: mentor
  pricedesc:
    title: 料金内訳
    description: 【チャットサポート30,000円】のみ
  addition1:
    title:
    description:
  addition2:
    title:
    description:
  update:
    title: 契約更新
    description:  3ヶ月毎に3ヶ月分の料金が発生致します。料金の支払日は更新日によって異なります。<br>(Q&A参照)<br>なお初回1ヶ月無料キャンペーンにつき、初回契約時のみ3ヶ月+無料1ヶ月の計4ヶ月の契約となります。<br>※解約、コースの変更は支払日の5営業日前までにご申告ください。
