# site settings
title: Interrupt LLC.
subtitle:
email: info@interrupt.technology
theme: forty_jekyll_theme
description: 経験豊富なメンバーが<br />ITに関するベストソリューションをご提案します。
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.interrupt.technology" # the base hostname & protocol for your site
author: Naoko Kubo
#street_address:
#city: 日野市
#state: 東京都
#zip_code: 191-0041
#country: 日本
#phone:
future: true
# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 7

# build settings
markdown: kramdown
kramdown:
 auto_ids: true
 hard_wrap: true
 syntax_highlighter: rouge

sass:
  style: compressed
